export BASE_IMAGE="vauxoo/odoo-140-image"
export PSQL_VERSION="11"
export VERSION="14.0"
export ODOO_REPO="vauxoo/odoo"
export ODOO_BRANCH="14.0"
export MAIN_APP="outpostnosara"
export TRAVIS_PYTHON_VERSION="3.8"
export TRAVIS_REPO_SLUG="Vauxoo/"
export COUNTRY="MX"
export CUSTOMER="outpostnosara"
export COVERAGE_MIN=80
export COVERAGE_PRECISION=2
export OPTIONS="--load=multi_pms_properties"
export INSTALL_OPTIONS="--load=multi_pms_properties"
